### ISSUE TITLE
Output file format

### ISSUE THREAD

**Issue by aardappel** [sylefeb/VoxSurf#4]
This appears to not be https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt but something else. What is it?

**Comment by sylefeb** [comment]
This is the format used by MagicaVoxel when exporting as 'slab'. I believe it is called 'slab6' and originates from the SLAB6 voxel editor http://www.advsys.net/ken/download.htm
(edit: now precised into code comments)
